### ISSUE TITLE
Meteor impact causes server lag in 1.18.1

### ISSUE THREAD

**Issue by vintage-seraph** [TaskaRaine/Meteoric-Expansion#11]
Not sure if this is a VS issue or an ME issue.
When a meteor impacts, the impact sound plays for about 10 seconds and the server lags.  The hardware is decent.

Thanks.

Environment: Iinux dedicated server: 
%Cpu(s):  0.8 us,  0.3 sy,  0.0 ni, 98.8 id,  0.1 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  31788.6 total,  22073.9 free,   3098.6 used,   6616.1 buff/cache

cpu:
          description: CPU
          product: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
          vendor: Intel Corp.
          physical id: 53
          bus info: cpu@0
          version: 6.60.3
          slot: SOCKET 1150
          size: 2499MHz
          capacity: 3900MHz
          width: 64 bits
          clock: 100MHz

Mod List:
'1499 Degrees.zip'
animalcages_v2.1.4.zip
AnvilMetalRecovery-1.0.1.zip
BetterRuinsv0.0.8.zip
Bullseye_2.5.0-rc.1.zip
canbeignited_v1.1.0.zip
CarryOn-1.18.0-rc.8_v1.0.0-rc.3.zip
FromGoldenCombs-1.18-v1.4.16-rc.2.zip
medievalexpansion-3.9.0.zip
MeteoricExpansion_V1.2.3.zip
paxel_v1.2.1.zip
PrimitiveSurvival3.1.6.zip
ResinOnAllSides-v1.0.0.zip
VisibleTerraPreta-Particles-v1.0.0.zip
'Wildcraft Trees-1.1.5.zip'
wildcraft-v1.6.4.zip
workbench-expansion-1.6.0.zip

**Comment by vintage-seraph** [comment]
Other note:  I am the only player right now.

**Comment by TaskaRaine** [comment]
Would there happen to be a server or client log associated with this? If it's possible to share those, that could give me some clues as to what the problem may be

**Comment by vintage-seraph** [comment]
Yep.  Looks like the server is polling to load a land claim object.
[server-main.txt](https://github.com/TaskaRaine/Meteoric-Expansion/files/11305315/server-main.txt)

**Comment by TaskaRaine** [comment]
Strange... that error is pointing to a type provided by the vanilla API. It should still exist, as far as I can see, and managed to get proper impacts on a 1.18.1 test world. This was single player locally hosted, though.  

I'll have to do a deeper dive to find out what's going on

**Comment by TaskaRaine** [comment]
This issue _should_ be resolved now. The mod just needed to be rebuilt with more recent Vintage Story files. Meteoric Expansion 1.2.4 is up on the [ModDB](https://mods.vintagestory.at/show/mod/78) now. 

Thanks for the report ^.^

**Comment by vintage-seraph** [comment]
Hello Taska,

Thank you for taking the time to tunnel into it.  :)

Tuesday, April 25, 2023, 7:52:16 PM, you wrote:

> This issue should be resolved now. The mod just needed to be rebuilt with more recent Vintage Story files. Meteoric Expansion 1.2.4 is up on the ModDB now.
> Thanks for the report ^.^
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
Best regards,
Robert Bowman
